export const textLabels = {
  buildingInstructionsLabel: "Building Instructions:",
  clickHereLabel: "Click Here",
  loadingLabel: "LOADING...",
  partQuantityLabel: "Number in Set: ",
  partNameLabel: "Part Name: ",
  partNumberLabel: "Part Number: ",
  partColorLabel: "Part Color: ",
  notOwned: "Not Owned",
  owned: "Owned",
  ownedLabel: "Owned: ",
  removeFromOwned: "Remove from Owned",
  addToOwned: "Add to Owned",
  themeLabel: "Theme: ",
  totalBricks: "Total Bricks: ",
  yearLabel: "Year: ",
} as const;
